/*
 * Copyright (c) 2025, Luke Wilde <luke@ladybird.org>
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

#include <LibJS/Runtime/Completion.h>
#include <LibJS/Runtime/GlobalObject.h>
#include <LibJS/Runtime/ValueInlines.h>
#include <LibWeb/HTML/Canvas/CanvasRenderingContext2DSettings.h>

namespace Web::HTML {

JS::ThrowCompletionOr<CanvasRenderingContext2DSettings> convert_value_to_settings_dictionary(JS::VM& vm, JS::Value value)
{
    // NOTE: This code was generated by the IDL code generator and then cleaned up.
    if (!value.is_nullish() && !value.is_object())
        return vm.throw_completion<JS::TypeError>(JS::ErrorType::NotAnObjectOfType, "CanvasRenderingContext2DSettings");

    CanvasRenderingContext2DSettings options {};

    auto alpha_property_value_0 = JS::js_undefined();
    if (value.is_object())
        alpha_property_value_0 = TRY(value.as_object().get("alpha"));

    bool alpha_value_0;

    if (!alpha_property_value_0.is_undefined())
        alpha_value_0 = alpha_property_value_0.to_boolean();
    else
        alpha_value_0 = true;

    options.alpha = alpha_value_0;

    auto color_space_property_value_1 = JS::js_undefined();
    if (value.is_object())
        color_space_property_value_1 = TRY(value.as_object().get("colorSpace"));

    Bindings::PredefinedColorSpace color_space_value_1 { Bindings::PredefinedColorSpace::Srgb };

    if (!color_space_property_value_1.is_undefined()) {
        auto color_space_property_value_1_string = TRY(color_space_property_value_1.to_string(vm));

        if (color_space_property_value_1_string == "srgb"sv)
            color_space_value_1 = Bindings::PredefinedColorSpace::Srgb;
        else if (color_space_property_value_1_string == "display-p3"sv)
            color_space_value_1 = Bindings::PredefinedColorSpace::DisplayP3;
        else
            return vm.throw_completion<JS::TypeError>(JS::ErrorType::InvalidEnumerationValue, color_space_property_value_1_string, "PredefinedColorSpace");
    }

    options.color_space = color_space_value_1;

    auto desynchronized_property_value_2 = JS::js_undefined();
    if (value.is_object())
        desynchronized_property_value_2 = TRY(value.as_object().get("desynchronized"));

    bool desynchronized_value_2;

    if (!desynchronized_property_value_2.is_undefined())
        desynchronized_value_2 = desynchronized_property_value_2.to_boolean();
    else
        desynchronized_value_2 = false;

    options.desynchronized = desynchronized_value_2;

    auto will_read_frequently_property_value_3 = JS::js_undefined();
    if (value.is_object())
        will_read_frequently_property_value_3 = TRY(value.as_object().get("willReadFrequently"));

    bool will_read_frequently_value_3;

    if (!will_read_frequently_property_value_3.is_undefined())
        will_read_frequently_value_3 = will_read_frequently_property_value_3.to_boolean();
    else
        will_read_frequently_value_3 = false;

    options.will_read_frequently = will_read_frequently_value_3;

    return options;
}

}
