// https://w3c.github.io/gamepad/#dom-gamepadbutton
[Exposed=Window]
interface GamepadButton {
    [FIXME] readonly attribute boolean pressed;
    [FIXME] readonly attribute boolean touched;
    [FIXME] readonly attribute double value;
};
